### ISSUE TITLE
Problem with recognizing images with query string (fix included)

### ISSUE THREAD

**Issue by Eccenux** [gilbitron/Nivo-Lightbox#18]
There is a slight problem that makes image preview appear with scrollbars on Chrome. It occurs e.g. on Drupal when you choose to have scaled image displayed instead of the original one.

The problem is that url looks like this "blah.jpg?some-stuff".

Simple fix - change this:

```
href.match(/\.(jpeg|jpg|gif|png)$/
```

To this:

```
href.match(/\.(jpeg|jpg|gif|png)($|\?)/
```

**Comment by fritzmg** [comment]
This is a more general problem. URLs to images aren't always a direct resource path. In addition to the problem with parameters as described above, your image URL could be something completely different, like http://placehold.it/350x150 or http://lorempixel.com/400/200

Having to artificially add a query string parameter that ends in jpg or png etc. is indeed messy and relatively complicated. It would make much more sense if you could force the lightbox type to image, as josh18 suggested.

**Comment by fritzmg** [comment]
Additionally, the hack of extending the `href` attribute with something like `&extension=.png` or just `&.png` does not work in case you are trying to open a public facebook image in the Nivo Lightbox.

Example:

* https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xfa1/v/t1.0-9/10612856_1668512703374234_835956123736768650_n.jpg?oh=1826e0ec6fdab4df2d660e8f024e73a7&oe=55D1A258&__gda__=1439758446_e0fcee60f00e442bb3125c8ad4ba39c3 vs.
* https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xfa1/v/t1.0-9/10612856_1668512703374234_835956123736768650_n.jpg?oh=1826e0ec6fdab4df2d660e8f024e73a7&oe=55D1A258&__gda__=1439758446_e0fcee60f00e442bb3125c8ad4ba39c3&.png
