### ISSUE TITLE
NivoLightbox and Infinite Scroll

### ISSUE THREAD

**Issue by martinb07** [gilbitron/Nivo-Lightbox#26]
Hi
I want to use the NivoLightbox with Paul Irish Infinite Scroll. After new content is loaded, the lightbox is not working on the new items. 
It look like the lightbox does not know that there are new elements and should be initialized again. On this page (-> http://www.infinite-scroll.com/lightbox-compatibility-code/) I found some code for other lightboxes. What do I have to do for the NivoLightbox to work with the inifinite scroll plugin?

Thanks
Regards
Martin

**Comment by ailedgarcia** [comment]
I'm getting the same error when clicking on my student examples lightbox imagesbut its only not working on mobile device (works fine on desktop computers on all current browsers).  Web address is:  http://www.ailedgarcia.com/112/#studentwork       Any and all help is appreciated :)
