### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by fritzmg** [gilbitron/Nivo-Lightbox#59]
http://docs.dev7studios.com/jquery-plugins/nivo-lightbox has been down for a while now.

**Comment by gilbitron** [comment]
Updated the link in the README.

**Comment by fritzmg** [comment]
It seems the documentation is down yet again? ( http://docs.dev7studios.com/category/10-nivo-lightbox )

**Comment by spencer-hill** [comment]
I found docs here: [http://docs.themeisle.com/category/492-nivo-lightbox](http://docs.themeisle.com/category/492-nivo-lightbox)
